POST http://localhost:8080/records/add
Content-Type: application/json

{
  "id": 2,
  "title": "z",
  "body": "s",
  "userId": "4"
}

###

GET http://localhost:8080/records
Accept: application/json


###

GET http://localhost:8080/records/2
Accept: application/json

###

GET http://localhost:8080/records/get/z
Accept: application/json

###

POST http://localhost:8080/records/import
Content-Type: application/json