POST http://localhost:8080/records/add
Content-Type: application/json

{
  "id": 2,
  "title": "z",
  "body": "s",
  "userId": "4"
}

###

GET http://localhost:8080/records
Accept: application/json

###

GET http://localhost:8080/records/get/z
Accept: application/json
